### ISSUE TITLE
Calculation prediction values

### ISSUE THREAD

**Issue by feyzazeynep** [Luferov/FuzzyLogicToolBox#2]
I want to train time series ANFIS model with your code. But how do I get the prediction values?
Which function should I use?
Also, can I separate the train test data and compare the test data with the prediction values?

**Comment by Luferov** [comment]
> I want to train time series ANFIS model with your code. But how do I get the prediction values? Which function should I use? Also, can I separate the train test data and compare the test data with the prediction values?

Is it actual?
